backend:
  name: git-gateway
  branch: dev
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio-post"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "White Logo Image", name: "logoWhite", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Hero, name: hero, widget: object, fields: [
              {label: Title, name: title, widget: markdown},
              {label: Subtitle, name: subtitle, widget: markdown},
              {label: ButtonTitle, name: buttonTitle, widget: string}
          ]}
          - {label: Work, name: work, widget: object, fields: [
              {label: Title, name: title, widget: markdown},
              {label: Subtitle, name: subtitle, widget: markdown},
              {label: Subheading, name: subheading, widget: markdown},
              {label: Logo1, name: workLogo1, widget: image},
              {label: Logo2, name: workLogo2, widget: image},
              {label: Logo3, name: workLogo3, widget: image},
              {label: Logo4, name: workLogo4, widget: image},
              {label: ButtonTitle, name: buttonTitle, widget: string}
          ]}
          - {label: Services, name: services, widget: object, fields: [
              {label: Title, name: title,  widget: markdown},
              {label: Subtitle, name: subtitle, widget: markdown},
              {label: Service1Title, name: service1Title,  widget: string},
              {label: Service1Subtitle, name: service1Subtitle, widget: string},
              {label: Service2Title, name: service2Title,  widget: string},
              {label: Service2Subtitle, name: service2Subtitle, widget: string},
              {label: Service3Title, name: service3Title,  widget: string},
              {label: Service3Subtitle, name: service3Subtitle, widget: string},
              {label: Service4Title, name: service4Title,  widget: string},
              {label: Service4Subtitle, name: service4Subtitle, widget: string},
              {label: ButtonTitle, name: buttonTitle, widget: string}
          ]}
          - {label: "Why Section", name: why, widget: object, fields: [
              {label: Title, name: title, widget: markdown},
              {label: Subtitle, name: subtitle, widget: markdown},
              {label: ButtonTitle, name: buttonTitle, widget: string}
          ]}

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Hero, name: hero, widget: object, fields: [
              {label: Subheading, name: subheading, widget: markdown},
              {label: Title, name: title, widget: markdown},
              {label: Subtitle, name: subtitle, widget: markdown},
              {label: ButtonTitle, name: buttonTitle, widget: string, required: false},
              {label: Button URL, name: buttonUrl, widget: string, required: false},
              {label: Image, name: image, widget: image}
          ]}
          - {label: Intro, name: intro, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: subtitle, name: subtitle, widget: markdown},
              {label: Button Title, name: buttonTitle, widget: string}
            ]}
          - {label: Partners, name: partners, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: subtitle, name: subtitle, widget: markdown},
              {label: Partner Logo 1, name: partnerLogo1, widget: image},
              {label: Partner Type 1, name: partnerType1, widget: text},
              {label: Button Text 1, name: partnerButtonTitle1, widget: text},
              {label: Button Url 1, name: partnerButtonLink1, widget: text},
              {label: Partner Logo 2, name: partnerLogo2, widget: image},
              {label: Partner Type 2, name: partnerType2, widget: text},
              {label: Button Text 2, name: partnerButtonTitle2, widget: text},
              {label: Button Url 2, name: partnerButtonLink2, widget: text},
              {label: Partner Logo 3, name: partnerLogo3, widget: image},
              {label: Partner Type 3, name: partnerType3, widget: text},
              {label: Button Text 3, name: partnerButtonTitle3, widget: text},
              {label: Button Url 3, name: partnerButtonLink3, widget: text}
            ]}
      - file: "src/pages/services/index.md"
        label: "Services Page"
        name: "services"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: Subheading, name: subheading, widget: markdown}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Service, name: services, widget: list, fields: [{label: Image, name: image, widget: image}, {label: ServiceTitle, name: serviceTitle, widget: string}, {label: ServiceSubtitle, name: serviceSubtitle, widget: markdown}]}]}
          - {label: CTA, name: cta, widget: object, fields: [{label: Title, name: title1, widget: string}, {label: Subtitle, name: subtitle1, widget: string}, {label: Button Title, name: buttonTitle1, widget: string}, {label: Title, name: title2, widget: string}, {label: Subtitle, name: subtitle2, widget: string}, {label: Button Title, name: buttonTitle2, widget: string}]}




















